import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import api from '../../api/client';

export default function UserDashboardPage({ view = 'projects' }) {
  const [projects, setProjects] = useState([]); const [inputs, setInputs] = useState({}); const [files, setFiles] = useState({}); const [qrOpen, setQrOpen] = useState(false);
  const load = async () => { try { const { data } = await api.get('/project-requests'); setProjects(data.data.projectRequests); } catch { toast.error('Unable to load projects'); } };
  useEffect(() => { load(); }, []);
  const send = async (id) => { const text=inputs[id]?.trim(); if(!text)return; await api.post(`/project-requests/${id}/messages`,{text}); setInputs({...inputs,[id]:''}); await load(); };
  const pay = async (id) => { const file=files[id]; if(!file)return toast.error('Upload your payment screenshot'); if(file.size>5*1024*1024)return toast.error('Screenshot must be under 5 MB'); const data=new FormData(); data.append('screenshot',file); try { await api.post(`/project-requests/${id}/payment`,data); toast.success('Payment screenshot sent for verification'); await load(); } catch(error){toast.error(error?.response?.data?.message||'Unable to upload payment proof');} };
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-black">{view==='messages'?'Project messages':view==='payments'?'Payments & delivery':'My projects'}</h1><p className="text-slate-600">Track every request, update and delivery securely.</p></div><a className="primary-button" href="/user/pre-book">Submit new project</a></div>
    {!projects.length&&<div className="soft-card p-10 text-center text-slate-600">No project submitted yet.</div>}
    {projects.map(p=><section key={p._id} className="soft-card overflow-hidden p-4 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-xs font-bold text-blue-700">{p.requestId} · {p.package} · ₹{p.amount?.toLocaleString('en-IN')}</div><h2 className="mt-1 text-xl font-black">{p.projectTitle}</h2><p className="text-sm text-slate-500">{p.projectCategory}</p></div><span className="rounded-full bg-blue-50 px-4 py-2 text-sm font-bold text-blue-700">{p.status}</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-gradient-to-r from-blue-600 to-cyan-400" style={{width:`${p.progress||0}%`}}/></div><div className="mt-1 text-right text-xs text-slate-500">{p.progress||0}% complete</div>
      {p.adminNotes&&<div className="mt-4 rounded-2xl bg-amber-50 p-4 text-sm"><b>Admin update:</b> {p.adminNotes}</div>}
      <div className="mt-5 rounded-2xl border p-4"><h3 className="font-bold">Project messages</h3><div className="mt-3 max-h-52 space-y-2 overflow-auto">{(p.messages||[]).map((m,i)=><div key={i} className={`w-fit max-w-[85%] rounded-2xl px-3 py-2 text-sm ${m.sender==='student'?'ml-auto bg-blue-600 text-white':'bg-slate-100'}`}>{m.text}</div>)}</div>{p.status!=='Delivered'?<div className="mt-3 flex flex-col gap-2 sm:flex-row"><input className="app-input" maxLength="4000" placeholder="Write a message..." value={inputs[p._id]||''} onChange={e=>setInputs({...inputs,[p._id]:e.target.value})}/><button className="primary-button" onClick={()=>send(p._id)}>Send</button></div>:<div className="mt-3 rounded-xl bg-slate-100 p-3 text-sm font-semibold text-slate-600">This project is completed and closed. Start a new booking for additional work.</div>}</div>
      {p.status==='Completed'&&!p.paymentScreenshotUploaded&&<div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 sm:p-5"><h3 className="font-black">Project ready — complete payment</h3><p className="mt-1 text-sm text-slate-600">Scan the QR, complete payment and upload the screenshot.</p><button onClick={()=>setQrOpen(true)} className="mx-auto my-4 block rounded-2xl border bg-white p-2 shadow-md transition hover:shadow-xl sm:mx-0"><img src="/payment-qr.png" className="h-56 w-56 rounded-xl object-contain sm:h-64 sm:w-64" alt="Payment QR"/></button><p className="mb-4 text-center text-xs font-semibold text-emerald-800 sm:text-left">Click the QR above to enlarge, scan and pay securely.</p><div className="flex flex-col gap-2 sm:flex-row"><input type="file" accept="image/png,image/jpeg,image/webp" className="app-input" onChange={e=>setFiles({...files,[p._id]:e.target.files?.[0]})}/><button className="primary-button shrink-0" onClick={()=>pay(p._id)}>Upload payment proof</button></div><p className="mt-2 text-xs text-slate-500">PNG, JPG or WebP · Maximum 5 MB</p></div>}
      {p.status==='Payment Submitted'&&<div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="font-black text-amber-900">Payment under review</div><p className="mt-1 text-sm text-amber-800">Your payment proof was submitted successfully. Once the review is completed, the project files, documentation and delivery details will be sent to your registered email address.</p></div>}
      {p.status==='Delivered'&&<div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 sm:p-5"><div className="font-black text-emerald-950">Project completed and delivered</div><p className="mt-1 text-sm text-emerald-800">Your complete project, documentation and available delivery links have been sent to your registered email address: <b>{p.email}</b>.</p><div className="mt-4 flex flex-col gap-2 sm:flex-row sm:flex-wrap">{p.deliveryUrl&&<a className="primary-button" href={p.deliveryUrl} target="_blank" rel="noreferrer">Download project from Drive</a>}{p.demoVideoUrl&&<a className="secondary-button" href={p.demoVideoUrl} target="_blank" rel="noreferrer">Watch demo video</a>}{p.deploymentUrl&&<a className="secondary-button" href={p.deploymentUrl} target="_blank" rel="noreferrer">Open live project</a>}</div></div>}
    </section>)}
    {qrOpen&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/85 p-3 backdrop-blur-sm" onClick={()=>setQrOpen(false)}><div className="relative w-full max-w-xl rounded-[28px] bg-white p-4 shadow-2xl sm:p-6" onClick={e=>e.stopPropagation()}><button onClick={()=>setQrOpen(false)} className="absolute right-3 top-3 h-10 w-10 rounded-full bg-slate-900 text-xl text-white">×</button><h2 className="pr-12 text-xl font-black">Scan and pay</h2><p className="text-sm text-slate-500">Use any supported payment application.</p><img src="/payment-qr.png" className="mx-auto mt-5 max-h-[70vh] w-full max-w-md rounded-2xl border object-contain" alt="Full-size payment QR"/><p className="mt-4 text-center text-sm font-semibold">Scan the QR, complete payment, then upload your payment screenshot.</p></div></div>}
  </div>;
}
