import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import api from '../../api/client';

const statuses = ['Under Review', 'More Information Required', 'Confirmed', 'In Development', 'Testing', 'Completed', 'Paid', 'Delivered', 'Rejected'];
export default function AdminDashboardPage({ view = 'dashboard' }) {
  const [requests, setRequests] = useState([]); const [drafts, setDrafts] = useState({});
  const load = async () => { try { const { data } = await api.get('/admin/requests'); setRequests(data.data.requests); } catch { toast.error('Unable to load admin data'); } };
  useEffect(() => { load(); }, []);
  const update = async (p, extra = {}) => { const d = drafts[p._id] || {}; if ((d.status || p.status) === 'Delivered' && !(d.deliveryUrl ?? p.deliveryUrl)) return toast.error('Add the Google Drive project link before delivery'); await api.patch(`/admin/requests/${p._id}`, { status: d.status || p.status, progress: d.progress ?? p.progress, adminNotes: d.adminNotes ?? p.adminNotes, deliveryUrl: d.deliveryUrl ?? p.deliveryUrl, demoVideoUrl: d.demoVideoUrl ?? p.demoVideoUrl, deploymentUrl: d.deploymentUrl ?? p.deploymentUrl, ...extra }); toast.success('Project updated'); await load(); };
  const message = async (id) => { const text = drafts[id]?.message?.trim(); if (!text) return; await api.post(`/admin/requests/${id}/messages`, { text }); setDrafts({ ...drafts, [id]: { ...drafts[id], message: '' } }); await load(); };
  const release = async (p) => { const d = drafts[p._id] || {}; if (!(d.deliveryUrl ?? p.deliveryUrl)) return toast.error('Add the Google Drive project link first'); try { const { data } = await api.post(`/admin/requests/${p._id}/release`, { deliveryUrl: d.deliveryUrl ?? p.deliveryUrl, demoVideoUrl: d.demoVideoUrl ?? p.demoVideoUrl, deploymentUrl: d.deploymentUrl ?? p.deploymentUrl }); data.data.emailSent ? toast.success('Project released and email sent') : toast.error('Released, but SMTP is not configured'); await load(); } catch (error) { toast.error(error?.response?.data?.message || 'Unable to release project'); } };
  return <div className="space-y-6"><div><h1 className="text-3xl font-black">Admin project control</h1><p className="text-slate-600">Confirm bookings, communicate, track development, verify payment and release delivery.</p></div>
    <div className="grid gap-4 md:grid-cols-3">{[['Requests', requests.length], ['In development', requests.filter(x => ['Confirmed','In Development','Testing'].includes(x.status)).length], ['Awaiting payment', requests.filter(x => ['Completed','Payment Submitted'].includes(x.status)).length]].map(([a,b]) => <div className="metric-card" key={a}><div className="text-sm text-slate-500">{a}</div><div className="text-3xl font-black">{b}</div></div>)}</div>
    {requests.map((p) => { const d = drafts[p._id] || {}; return <section className="soft-card p-6" key={p._id}><div className="flex flex-wrap justify-between gap-3"><div><div className="text-xs font-bold text-blue-700">{p.requestId} · {p.package} · ₹{p.amount?.toLocaleString('en-IN')}</div><h2 className="text-xl font-black">{p.projectTitle}</h2><p className="text-sm text-slate-600">{p.studentName} · {p.email} · {p.phone}</p></div><span className="rounded-full bg-slate-100 px-4 py-2 text-sm font-bold">{p.status}</span></div><p className="mt-4 rounded-xl bg-slate-50 p-3 text-sm">{p.projectDescription}</p>
      <div className="mt-4 grid gap-3 md:grid-cols-2"><select className="app-select" value={d.status || p.status} onChange={e => setDrafts({...drafts,[p._id]:{...d,status:e.target.value}})}>{p.status === 'New' && <option>New</option>}{p.status === 'Payment Submitted' && <option>Payment Submitted</option>}{statuses.map(s => <option key={s}>{s}</option>)}</select><input type="number" min="0" max="100" className="app-input" value={d.progress ?? p.progress ?? 0} onChange={e => setDrafts({...drafts,[p._id]:{...d,progress:Number(e.target.value)}})} placeholder="Progress %"/><textarea className="app-textarea md:col-span-2" value={d.adminNotes ?? p.adminNotes ?? ''} onChange={e => setDrafts({...drafts,[p._id]:{...d,adminNotes:e.target.value}})} placeholder="Status note visible to customer"/><input className="app-input" value={d.deliveryUrl ?? p.deliveryUrl ?? ''} onChange={e => setDrafts({...drafts,[p._id]:{...d,deliveryUrl:e.target.value}})} placeholder="Google Drive project folder/ZIP link (required)"/><input className="app-input" value={d.demoVideoUrl ?? p.demoVideoUrl ?? ''} onChange={e => setDrafts({...drafts,[p._id]:{...d,demoVideoUrl:e.target.value}})} placeholder="Google Drive demo video link"/><input className="app-input md:col-span-2" value={d.deploymentUrl ?? p.deploymentUrl ?? ''} onChange={e => setDrafts({...drafts,[p._id]:{...d,deploymentUrl:e.target.value}})} placeholder="Live project deployment URL (optional)"/></div><button className="primary-button mt-3 w-full sm:w-auto" onClick={() => update(p)}>Save project update</button>
      {p.paymentScreenshotUploaded && <div className="mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><div className="font-black text-emerald-950">Payment proof received</div><img src={`/api/admin/requests/${p._id}/payment-screenshot`} className="mt-3 max-h-80 w-full rounded-xl border bg-white object-contain sm:max-w-md" alt={`Payment proof from ${p.studentName}`}/><button onClick={() => update(p,{status:'Paid'})} className="primary-button mt-3 w-full sm:w-auto">Verify payment</button></div>}
      {p.status === 'Paid' && <div className="mt-4 rounded-2xl border border-blue-200 bg-blue-50 p-4"><div className="font-black text-blue-950">Payment verified — ready to deliver</div><p className="mt-1 text-sm text-blue-800">This emails all delivery links to {p.email} and marks the project Delivered.</p><button onClick={() => release(p)} className="primary-button mt-3 w-full sm:w-auto">Release project & send email</button></div>}
      <div className="mt-4 max-h-44 space-y-2 overflow-auto">{(p.messages || []).map((m,i)=><div key={i} className={`w-fit max-w-[85%] rounded-xl px-3 py-2 text-sm ${m.sender === 'admin' ? 'ml-auto bg-slate-900 text-white':'bg-slate-100'}`}>{m.text}</div>)}</div><div className="mt-2 flex gap-2"><input className="app-input" value={d.message || ''} onChange={e=>setDrafts({...drafts,[p._id]:{...d,message:e.target.value}})} placeholder="Reply to customer..."/><button className="primary-button" onClick={()=>message(p._id)}>Send</button></div>
    </section>})}</div>;
}
