import { ArrowUpRight, Clock3, MessageCircle, Phone, ShieldCheck } from 'lucide-react';

const whatsappUrl = 'https://wa.me/918088379279?text=Hello%20ProjectDesk%2C%20I%20want%20to%20discuss%20my%20project.';
export default function ContactPage() {
  return <main className="mx-auto max-w-5xl px-4 py-14">
    <div className="text-center"><div className="pill-tag mb-4">WhatsApp support</div><h1 className="text-4xl font-black md:text-5xl">Let’s discuss your project</h1><p className="mx-auto mt-4 max-w-2xl text-slate-600">Contact us directly on WhatsApp for planning, package selection, timelines and booking.</p></div>
    <section className="mx-auto mt-10 overflow-hidden rounded-[32px] bg-gradient-to-br from-emerald-600 via-emerald-700 to-slate-900 p-6 text-white shadow-2xl md:p-10"><div className="grid items-center gap-8 md:grid-cols-[1fr,auto]"><div><div className="inline-flex rounded-2xl bg-white/15 p-4"><MessageCircle size={36}/></div><h2 className="mt-5 text-3xl font-black">Chat with ProjectDesk</h2><p className="mt-3 max-w-xl text-emerald-50">Send your project topic, technology, deadline and requirements through WhatsApp.</p><div className="mt-6 flex flex-wrap gap-4 text-sm text-emerald-50"><span className="flex items-center gap-2"><Clock3 size={17}/> Quick response</span><span className="flex items-center gap-2"><ShieldCheck size={17}/> Private conversation</span></div></div><div className="rounded-3xl bg-white p-5 text-center text-slate-900 shadow-xl"><div className="text-xs font-bold uppercase tracking-widest text-emerald-700">WhatsApp number</div><a href="tel:+918088379279" className="mt-2 flex items-center justify-center gap-2 text-xl font-black"><Phone size={20}/> +91 80883 79279</a><a href={whatsappUrl} target="_blank" rel="noreferrer" className="mt-5 flex items-center justify-center gap-2 rounded-full bg-emerald-600 px-6 py-3 font-bold text-white hover:bg-emerald-700">Open WhatsApp <ArrowUpRight size={18}/></a></div></div></section>
  </main>;
}
