import { motion } from 'framer-motion';
import { ArrowRight, BadgeCheck, Blocks, BrainCircuit, CheckCircle2, ChevronRight, CircleDollarSign, CloudDownload, Code2, FileCheck2, FileUp, LayoutDashboard, LockKeyhole, MessageCircle, QrCode, Rocket, ShieldCheck, Smartphone, Sparkles } from 'lucide-react';

const reveal = { initial: { opacity: 0, y: 12 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: '140px 0px' }, transition: { duration: .28, ease: 'easeOut' } };
const journey = [
  ['01', LockKeyhole, 'Sign in securely', 'Continue with Google or use your ProjectDesk email account to access your private workspace.'],
  ['02', FileUp, 'Submit your project', 'Add the topic, category, technology stack, features, deadline and complete project requirements.'],
  ['03', FileCheck2, 'Choose a package', 'Select Basic or Premium based on the files, documentation, video and deployment support you need.'],
  ['04', MessageCircle, 'Stay connected', 'Follow progress and send unlimited project-specific messages from your secure dashboard.'],
  ['05', QrCode, 'Pay after completion', 'When your project is ready, scan the payment QR and upload a clear payment screenshot for verification.'],
  ['06', CloudDownload, 'Receive delivery', 'After verification, receive project files, documentation, video and available deployment links by email and dashboard.'],
];
const services = [[Code2,'Web applications'],[LayoutDashboard,'MERN stack'],[BrainCircuit,'AI & ML'],[Smartphone,'Mobile applications'],[Sparkles,'Data science'],[Blocks,'Blockchain']];
const requirements = ['Project title and detailed topic','Preferred technology stack','Expected modules and features','College, department and semester','Deadline and project type','Reference files or special instructions'];

export default function LandingPage() {
  return <div className="overflow-hidden pb-20">
    <div className="border-b border-amber-200 bg-gradient-to-r from-amber-50 via-orange-50 to-amber-50 px-4 py-2.5 text-center text-xs font-bold text-amber-900 sm:text-sm"><span className="mr-2 inline-block animate-pulse">●</span> Limited development slots available — submit your project early to reserve your delivery window.</div>
    <section className="relative border-b border-slate-200/70">
      <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_15%_20%,rgba(37,99,235,.16),transparent_28%),radial-gradient(circle_at_85%_25%,rgba(6,182,212,.16),transparent_26%)]" />
      <div className="mx-auto grid min-h-[680px] max-w-7xl items-center gap-12 px-4 py-16 lg:grid-cols-[1.05fr,.95fr]">
        <motion.div initial={{opacity:0,x:-30}} animate={{opacity:1,x:0}} transition={{duration:.65}}>
          <div className="pill-tag mb-5"><Sparkles size={13} className="mr-2"/> End-to-end project delivery</div>
          <h1 className="max-w-3xl text-4xl font-black leading-[1.08] tracking-tight text-slate-950 sm:text-5xl lg:text-6xl">From your first idea to a <span className="bg-gradient-to-r from-blue-700 to-cyan-500 bg-clip-text text-transparent">finished project.</span></h1>
          <p className="mt-6 max-w-2xl text-base leading-7 text-slate-600 sm:text-lg">Submit your requirements, communicate throughout development, track every update, pay securely after completion and receive your complete delivery online.</p>
          <div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="/user/pre-book" className="primary-button px-7 py-3.5">Reserve your slot <ArrowRight size={17}/></a><a href="#how-it-works" className="secondary-button px-7 py-3.5">See how it works</a></div><p className="mt-3 flex items-center gap-2 text-xs font-semibold text-amber-700"><span className="h-2 w-2 animate-pulse rounded-full bg-amber-500"/> Hurry—current project slots are filling quickly.</p>
          <div className="mt-9 grid grid-cols-2 gap-3 sm:grid-cols-4">{[['2','Projects booked'],['1','Completed'],['99%','Satisfaction'],['98%','On-time']].map(([value,label],i)=><motion.div key={label} initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:.25+i*.08}} className="metric-card"><div className="text-2xl font-black">{value}</div><div className="text-xs text-slate-500">{label}</div></motion.div>)}</div>
        </motion.div>

        <motion.div initial={{opacity:0,scale:.94,y:20}} animate={{opacity:1,scale:1,y:0}} transition={{duration:.7,delay:.12}} className="relative">
          <div className="absolute -inset-8 -z-10 rounded-full bg-blue-500/15 blur-3xl"/><div className="rounded-[32px] border border-white/20 bg-slate-950 p-4 text-white shadow-[0_35px_90px_-35px_rgba(15,23,42,.8)] sm:p-6">
            <div className="flex items-center justify-between"><div><div className="text-xs text-slate-400">Student workspace</div><div className="mt-1 font-bold">AI Meeting Intelligence</div></div><span className="rounded-full bg-emerald-400/15 px-3 py-1 text-xs font-bold text-emerald-300">In development</span></div>
            <div className="mt-6 rounded-3xl bg-white/10 p-4"><div className="flex justify-between text-sm"><span>Overall progress</span><span className="font-bold">74%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><motion.div initial={{width:0}} animate={{width:'74%'}} transition={{duration:1.4,delay:.5}} className="h-full rounded-full bg-gradient-to-r from-cyan-400 to-blue-500"/></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-white/10 p-4"><MessageCircle size={19} className="text-cyan-300"/><div className="mt-3 text-sm font-bold">Project messages</div><div className="mt-1 text-xs text-slate-400">Ask questions and share updates</div></div><div className="rounded-2xl bg-white/10 p-4"><ShieldCheck size={19} className="text-emerald-300"/><div className="mt-3 text-sm font-bold">Private tracking</div><div className="mt-1 text-xs text-slate-400">Only your projects are visible</div></div></div></div>
            <div className="mt-4 flex items-center gap-3 rounded-2xl border border-white/10 p-3"><div className="rounded-xl bg-blue-500/20 p-2"><Rocket size={18}/></div><div className="min-w-0"><div className="text-sm font-bold">Latest update</div><div className="truncate text-xs text-slate-400">Core modules completed, testing started</div></div><ChevronRight className="ml-auto text-slate-500" size={18}/></div>
          </div>
        </motion.div>
      </div>
    </section>

    <section id="how-it-works" className="mx-auto max-w-7xl px-4 py-20"><motion.div {...reveal} className="mx-auto max-w-3xl text-center"><div className="pill-tag mb-4">Simple and transparent</div><h2 className="text-3xl font-black sm:text-4xl">Your complete project journey</h2><p className="mt-4 text-slate-600">Every stage is clear, trackable and available from your private dashboard.</p></motion.div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{journey.map(([number,Icon,title,desc],i)=><motion.article key={title} {...reveal} transition={{duration:.5,delay:(i%3)*.08}} className="group soft-card relative overflow-hidden p-6 transition hover:-translate-y-1 hover:border-blue-200"><div className="absolute right-5 top-4 text-5xl font-black text-slate-100 transition group-hover:text-blue-50">{number}</div><div className="relative inline-flex rounded-2xl bg-blue-50 p-3 text-blue-700"><Icon size={22}/></div><h3 className="relative mt-5 text-xl font-black">{title}</h3><p className="relative mt-2 text-sm leading-6 text-slate-600">{desc}</p></motion.article>)}</div></section>

    <section className="bg-slate-950 py-20 text-white"><div className="mx-auto grid max-w-7xl gap-12 px-4 lg:grid-cols-2 lg:items-center"><motion.div {...reveal}><div className="inline-flex rounded-full bg-blue-500/15 px-3 py-1 text-xs font-bold uppercase tracking-widest text-blue-300">Before you submit</div><h2 className="mt-5 text-3xl font-black sm:text-4xl">Tell us exactly what you need</h2><p className="mt-4 max-w-xl leading-7 text-slate-300">Clear requirements help create an accurate plan and smoother delivery. You can add further details later through project messages.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{requirements.map(item=><div key={item} className="flex gap-3 rounded-2xl bg-white/5 p-3 text-sm text-slate-200"><CheckCircle2 size={18} className="shrink-0 text-cyan-400"/>{item}</div>)}</div></motion.div><motion.div {...reveal} className="rounded-[30px] border border-white/10 bg-white/5 p-5 sm:p-7"><div className="flex items-center gap-3"><div className="rounded-2xl bg-blue-600 p-3"><FileUp size={22}/></div><div><div className="font-black">Project submission</div><div className="text-xs text-slate-400">Structured requirements form</div></div></div><div className="mt-6 space-y-3">{['Project topic and category','Required technologies','Expected features and deadline','Basic or Premium package'].map((item,i)=><motion.div key={item} initial={{opacity:0,x:20}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{delay:i*.1}} className="flex items-center gap-3 rounded-2xl bg-white/10 p-4"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-cyan-400 text-xs font-black text-slate-950">{i+1}</span><span className="text-sm font-semibold">{item}</span><BadgeCheck className="ml-auto text-emerald-300" size={18}/></motion.div>)}</div></motion.div></div></section>

    <section className="mx-auto max-w-7xl px-4 py-20"><div className="grid gap-6 lg:grid-cols-2"><motion.article {...reveal} className="rounded-[32px] border border-blue-100 bg-gradient-to-br from-blue-50 to-cyan-50 p-6 sm:p-9"><CircleDollarSign className="text-blue-700" size={36}/><h2 className="mt-5 text-3xl font-black">Pay only when your project is ready</h2><p className="mt-3 leading-7 text-slate-600">When development is marked complete, the payment area becomes available in your dashboard.</p><div className="mt-6 space-y-3">{['Open the completed project','Click the QR to enlarge it','Scan and complete payment','Upload a clear payment screenshot','Wait for verification and delivery'].map((x,i)=><div key={x} className="flex items-center gap-3 rounded-2xl bg-white/80 p-3 text-sm font-semibold"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-blue-700 text-xs text-white">{i+1}</span>{x}</div>)}</div><div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><b>Payment proof:</b> Upload a readable PNG, JPG or WebP screenshot, maximum 5 MB.</div></motion.article>
      <motion.article {...reveal} className="rounded-[32px] border border-slate-200 bg-white p-6 shadow-soft sm:p-9"><CloudDownload className="text-emerald-600" size={36}/><h2 className="mt-5 text-3xl font-black">A professional final delivery</h2><p className="mt-3 leading-7 text-slate-600">After payment verification, your completed project becomes read-only and the delivery is sent to your registered email.</p><div className="mt-6 space-y-3">{['Complete project files through Google Drive','Project documentation included with Premium','Demo video when included in your package','Optional live deployment URL','Delivery links retained on your dashboard'].map(x=><div key={x} className="flex gap-3 rounded-2xl bg-slate-50 p-4 text-sm"><CheckCircle2 className="shrink-0 text-emerald-600" size={19}/>{x}</div>)}</div></motion.article></div></section>

    <section className="mx-auto max-w-7xl px-4 pb-20"><motion.div {...reveal} className="text-center"><div className="pill-tag mb-4">What we build</div><h2 className="text-3xl font-black sm:text-4xl">Development across modern technologies</h2></motion.div><div className="mt-9 grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6">{services.map(([Icon,label],i)=><motion.div key={label} {...reveal} transition={{delay:i*.05}} className="soft-card flex min-h-36 flex-col items-center justify-center p-4 text-center"><Icon className="text-blue-700" size={27}/><div className="mt-3 text-sm font-bold">{label}</div></motion.div>)}</div></section>

    <section className="mx-auto max-w-7xl px-4"><motion.div {...reveal} className="overflow-hidden rounded-[36px] bg-gradient-to-r from-blue-700 via-blue-600 to-cyan-500 p-7 text-white shadow-2xl sm:p-10"><div className="flex flex-col items-start justify-between gap-7 lg:flex-row lg:items-center"><div><h2 className="text-3xl font-black sm:text-4xl">Ready to start your project?</h2><p className="mt-3 max-w-2xl text-blue-50">Create your secure workspace, submit the requirements and track the complete journey from one place.</p></div><div className="flex w-full flex-col gap-3 sm:w-auto sm:flex-row"><a href="/user/pre-book" className="inline-flex items-center justify-center gap-2 rounded-full bg-white px-6 py-3 font-bold text-blue-700">Submit project <ArrowRight size={17}/></a><a href="https://wa.me/918088379279" target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-full border border-white/30 px-6 py-3 font-bold">WhatsApp us</a></div></div></motion.div></section>
  </div>;
}
